db:
  build: machines/db
  ports:
    - 3301:3306
  environment:
    - MYSQL_USER=root
    - MYSQL_PASS=root
web:
  build: machines/web
  links:
    - db
  ports:
    - 8080:80
  volumes:
    - ./application:/var/www/html

